language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux
- osx
before_install:
- ./scripts/install-git-lfs.sh # linux-only
- ./scripts/install-cmake-ninja-flex.sh # .tar.bz2 on linux, brew on mac
script:
- git submodule update --init
- cd llvm-build
- cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ../llvm
- ninja
- export PATH=`pwd`/bin:$PATH
- cd ../rhine-build
- ../scripts/invoke-cmake-for-rhine.sh # -DFLEX_EXECUTABLE= extra on linux
- ninja check
branches:
  only: master
cache:
  ccache: true
  directories: llvm-build
notifications:
  email: false
  slack:
    secure: EUnwvQ3BtdbZb0/JhE5Jk+czLYg/n0RsvX9sJ/nE1aWFRqlEXJo3U0ehRJf5bTTVFVXqVwzWFxvUmV4mi0BsHAwdWrjJt+9JFVjCuAt9l/1aSznAfdasBUFiczMOg6nD8LJwk76OWXGpp5mr6FfO4Df9wUK4dm0t+mTFiL2RRXlaarPE2LaN3HvGCUWPDw/Izf6+I7oYrhvS8cjSgH+Uo6G9XEIcQIjX5uCTlMa8Wt/iwVtxH6amU1j6m92u/1e1mXGqUeEozP7WPo4edpuqxqjfVvGJdAcvpRZmv/nB3CSVtnfA27XcGQp4SQrsDgIJxbUDmXGgBo1bpwOuUH0A/Z8dDaHGD7cig6rW9fA1zjrACtl84ebhl+/reQJhOzUmo143+4Mt5gxmIpIuEtg7kRtCu6Yz/qXWZhOqADwAgctTkT3hXkgAyrfRGTSHwpfyxIA2uj9+o3YqqAjJ14MjPSP0ipxFhjcjDUTEdztdp6oNJo7fiI8oi1cv4W8m62C6MglLhg4HNEQswzgasti7X4iWC4RC56j9wbfNoOP7saHHo3F+UrjDrAje+SVmLJmds98kKYY4YtweiPSxvNnvi+AS6JUXuHKEt64yW11EjkvHIVbnVnODA0GdEk4LoRIBZCZReInqFBsuyKyjfw1t8EX/Z6vFMOrqEMtvT1sEucg=
